# Site settings
title: Peter Flach's recent presentations (Reveal.js only)
email: Peter.Flach@bristol.ac.uk
website: "http://flach.github.io"
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "/slides/" # the subpath of your site, e.g. /blog/
author: Peter Flach
affiliation: (University of Bristol)
footernote: Made with Reveal.js
style: "pf"

# Build settings
markdown: kramdown
exclude: 
  - Obsidian/2023_xai.md
  - Obsidian/2023_dsai.md  
  - Obsidian/2024_porto.md
  - Obsidian/2025_recife_2.md
  